### ISSUE TITLE
Possible bug with getQueryParam

### ISSUE THREAD

**Issue by nmoinvaz** [webarthur/ideal.js#1]
I am not 100% sure if this is a bug, but I think the getQueryParams fail to get the full value for the last query parameter. When that function checks `i===l-1` in this instance it should be doing `v += (c == '+') ? ' ' : c`. You can reproduce this bug by trying to retrieve the last query string parameter in a query string in which case the last character is cut off.

**Comment by webarthur** [comment]
Thanks @nmoinvaz. The bug has been fixed.
